# Data sources

The World happiness data was generated by Gallup World Poll and it is accessible through the website of World Happiness report. The world happiness report is the publication of the Sustainable Development Solutions Network(SDSN). SDSN was launched by United Nations to support sustainable development. It can be download directly from the world happiness report website. We collected the happiness record from 2016 to 2019. There are 11 features in each dataframe. 

They are Country,Happiness score, Whisker-high, Whisker-low, GDP per capita, Social support, Healthy life expectancy, Freedom to make life choices, Generosity,Perceptions of corruption, Dystopia (2.33) + residual. Happiness score is a ladder score from 0 to 10. Higher score indicate a happier life. Health life expectancy indicates the expected life time from birth of residents in each country. Freedom to make life choices indicate people's level of freedom in choosing what to do with their life. Social support indicates whether there are relatives or friends ready to help you when you get into trouble. Generosity shows the willingness of donate their money to charities. The perceptions of corruption shows whether the residents believe there are perception issues in their governments. 

One of the issue of the data is that number of countries are not the same in between 2016 and 2019. This issue is caused by the fact that there is new country established every year. Another issue is also the standardized issue. The names of the six factors are different in each dataframe. In order to be able to combine them into one dataframe, we need to standardized their name. These preprocessing code will be published in the cleaning chapter. 