# Conclusion

In general, this project explained the happiness index, which is an extremely important social index for any country, from three perspectives, including a general overview, analysis of special regions, and time series analysis. First of all, the first part is a general overview. Through it, we can have a general feeling that GDP is the most important for a country’s happiness index. However, for those developed countries in Europe, GDP is not so important, they pay more attention to freedom or social support. In comparison, most developing countries are diversified. In other words, the scores of each part of them are not particularly high, and there is room for improvement. The second part mainly analyzes the high happiness index of a small number of developing countries after the overall observation of the first part. After calculating the specific parameters, we locked these countries in Latin America. Specifically, for these countries, although their per capita GDP is very low, the dedication spirit of the society is very strong, which is an important factor that cannot be ignored. Also, compared with other regions, people in these countries live longer and have a higher degree of freedom in social choice. All these factors add up to create high happiness indexes in some low-income countries. Of course, due to the lack of data, we cannot get more specific and detailed conclusions from it. The main thing is to stay at the qualitative analysis level, and we cannot do more with the predictive function of machine learning. This is also a difficult problem we encountered in this project. We can only leave you with some guesses. When it comes to time series analysis, we first calculate the changes in the happiness index of each country in the past four years, and secondly, select the 10 countries with the largest growth as our main analysis objects. From this, we can see that these countries are all developing countries, and their happiness index, per capita GDP, and other parameters are all at a low level. Therefore, they also have huge room for growth. Finally, from these 10 countries, we selected the most distinctive country, Honduras. This country has grown at almost the same growth rate for three consecutive years. By 2019, the country’s happiness index has reached a level of nearly 6, which is on par with the developed countries in Asia, Japan, and South Korea.

Of course, the topic of happiness index has always been paid attention to, and its judging criteria are also very different in the eyes of many people, especially when facing different races and cultures. We hope that in the future when the world blends more thoroughly, the evaluation criteria of the happiness index can be improved so that governments and people of all ethnic groups can provide a more objective and realistic reference when making decisions.