--- 
title: "Recipe of Happiness"
author: "Yiwei Ren, Jing Lu, Xiaorui Zhang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction
Happiness has been studied for many years. Governments in all different countries tried to quantified happiness to help them improve their residents' overall satisfaction. World happiness provides essential factors for quantifying happiness. These are freedom, social support, GDP per capita, percentage of corruption, generosity, and healthy life expectancy. We will discuss the meaning of all these six factors in the data chapter. 

Therefore, in our project, we provide an analysis to show different recipes to gain happiness. That is: what are the recipes of happiness? Specifically, we will first study the success of the countries that have the highest happiness score. Next, we will focus on those outlier countries, especially Latin America. Among all the developing countries, why the countries in Latin America have relatively higher happiness scores? Then we will bring our sight to those countries that have huge improvements in their happiness scores from 2016 to 2019. 

Our team members are Yiwei Ren, Jing Lu and Xiaowei Zhang. Jing Lu was responsible for the Missing data and the first section of our topic: What are some most important features of happiness? Yiwei Ren was responsible for the data preprocessing and also the second section of our topic: what is the success of Latin America? Xiaorui Zhang was responsible for our conclusions and the last section of our topic: what is the secret of countries with huge improvement?

